// <auto-generated>
// Code generated by OpenAPI Generator (aspnetcore-minimalapi)
// Changes to this file will be overwritten when regenerating.
// </auto-generated>

using MediatR;
using PetstoreApi.DTOs;

namespace PetstoreApi.Queries;

/// <summary>
/// Query for GetPetById operation
/// 
/// Find pet by ID
/// 
/// </summary>
public record GetPetByIdQuery : IRequest<PetDto>
{
    /// <summary>
    /// ID of pet to return
    /// </summary>
    public long petId { get; init; }

}
