// <auto-generated>
// Code generated by OpenAPI Generator (aspnetcore-minimalapi)
// Changes to this file will be overwritten when regenerating.
// </auto-generated>

using MediatR;
using PetstoreApi.DTOs;

namespace PetstoreApi.Commands;

/// <summary>
/// Command for DeleteOrder operation
/// 
/// Delete purchase order by ID
/// 
/// </summary>
public record DeleteOrderCommand : IRequest<bool>
{
    /// <summary>
    /// ID of the order that needs to be deleted
    /// </summary>
    public string orderId { get; init; }

}
