// <auto-generated>
// Code generated by OpenAPI Generator (aspnetcore-minimalapi)
// Changes to this file will be overwritten when regenerating.
// </auto-generated>

using MediatR;
using PetstoreApi.DTOs;

namespace PetstoreApi.Commands;

/// <summary>
/// Command for DeletePet operation
/// 
/// Deletes a pet
/// 
/// </summary>
public record DeletePetCommand : IRequest<bool>
{
    /// <summary>
    /// Pet id to delete
    /// </summary>
    public long petId { get; init; }

    /// <summary>
    /// 
    /// </summary>
    public string? apiKey { get; init; } = default!;

}
