// <auto-generated>
// Code generated by OpenAPI Generator (aspnetcore-minimalapi)
// Changes to this file will be overwritten when regenerating.
// </auto-generated>

using MediatR;
using PetstoreApi.DTOs;

namespace PetstoreApi.Commands;

/// <summary>
/// Command for PlaceOrder operation
/// 
/// Place an order for a pet
/// 
/// </summary>
public record PlaceOrderCommand : IRequest<OrderDto>
{
    /// <summary>
    /// order placed for purchasing the pet
    /// </summary>
    public PlaceOrderDto order { get; init; }

}
