// <auto-generated>
// Code generated by OpenAPI Generator (aspnetcore-minimalapi)
// Changes to this file will be overwritten when regenerating.
// </auto-generated>

using MediatR;
using PetstoreApi.DTOs;

namespace PetstoreApi.Commands;

/// <summary>
/// Command for UpdatePetWithForm operation
/// 
/// Updates a pet in the store with form data
/// 
/// </summary>
public record UpdatePetWithFormCommand : IRequest<Unit>
{
    /// <summary>
    /// ID of pet that needs to be updated
    /// </summary>
    public long petId { get; init; }

    /// <summary>
    /// Updated name of the pet
    /// </summary>
    public string? name { get; init; } = default!;

    /// <summary>
    /// Updated status of the pet
    /// </summary>
    public string? status { get; init; } = default!;

}
