// <auto-generated>
// Code generated by OpenAPI Generator (aspnetcore-minimalapi)
// Changes to this file will be overwritten when regenerating.
// </auto-generated>

using MediatR;
using PetstoreApi.DTOs;

namespace PetstoreApi.Commands;

/// <summary>
/// Command for UpdateUser operation
/// 
/// Updated user
/// 
/// </summary>
public record UpdateUserCommand : IRequest<Unit>
{
    /// <summary>
    /// name that need to be deleted
    /// </summary>
    public string username { get; init; }

    /// <summary>
    /// Updated user object
    /// </summary>
    public UpdateUserDto user { get; init; }

}
