// <auto-generated>
// Code generated by OpenAPI Generator (aspnetcore-minimalapi)
// Changes to this file will be overwritten when regenerating.
// </auto-generated>

using MediatR;
using PetstoreApi.DTOs;

namespace PetstoreApi.Commands;

/// <summary>
/// Command for UploadFile operation
/// 
/// uploads an image
/// 
/// </summary>
public record UploadFileCommand : IRequest<ApiResponseDto>
{
    /// <summary>
    /// ID of pet to update
    /// </summary>
    public long petId { get; init; }

    /// <summary>
    /// Additional data to pass to server
    /// </summary>
    public string? additionalMetadata { get; init; } = default!;

    /// <summary>
    /// file to upload
    /// </summary>
    public System.IO.Stream? file { get; init; } = default!;

}
