// <auto-generated>
// Code generated by OpenAPI Generator (aspnetcore-minimalapi)
// Changes to this file will be overwritten when regenerating.
// </auto-generated>

using System;
using System.Collections.Generic;
using PetstoreApi.Converters;

namespace PetstoreApi.DTOs;


/// <summary>
/// DTO for  operation
/// 
/// Describes the result of uploading an image resource
/// 
/// </summary>
public record ApiResponseDto
{



    /// <summary>
    /// 
    /// </summary>
    public int? Code { get; init; } = default!;

    /// <summary>
    /// 
    /// </summary>
    public string? Type { get; init; } = default!;

    /// <summary>
    /// 
    /// </summary>
    public string? Message { get; init; } = default!;

}
