// <auto-generated>
// Code generated by OpenAPI Generator (aspnetcore-minimalapi)
// Changes to this file will be overwritten when regenerating.
// </auto-generated>

using System;
using System.Collections.Generic;
using PetstoreApi.Converters;

namespace PetstoreApi.DTOs;


/// <summary>
/// DTO for  operation
/// 
/// A pet for sale in the pet store
/// 
/// </summary>
public record PetDto
{






    /// <summary>
    /// pet status in the store
    /// </summary>
    /// <value>pet status in the store</value>
    [System.Text.Json.Serialization.JsonConverter(typeof(PetstoreApi.Converters.EnumMemberJsonConverter<StatusEnum>))]
    public enum StatusEnum
    {
        
        /// <summary>
        /// Enum AvailableEnum for available
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("available")]
        AvailableEnum = 1,
        
        /// <summary>
        /// Enum PendingEnum for pending
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("pending")]
        PendingEnum = 2,
        
        /// <summary>
        /// Enum SoldEnum for sold
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("sold")]
        SoldEnum = 3
    }


    /// <summary>
    /// 
    /// </summary>
    public long? Id { get; init; } = default!;

    /// <summary>
    /// 
    /// </summary>
    public CategoryDto? Category { get; init; } = default!;

    /// <summary>
    /// 
    /// </summary>
    public string Name { get; init; }

    /// <summary>
    /// 
    /// </summary>
    public List<string> PhotoUrls { get; init; }

    /// <summary>
    /// 
    /// </summary>
    public List<TagDto>? Tags { get; init; } = default!;

    /// <summary>
    /// pet status in the store
    /// </summary>
    [System.Text.Json.Serialization.JsonConverter(typeof(PetstoreApi.Converters.EnumMemberJsonConverter<StatusEnum>))]
    public StatusEnum? Status { get; init; } = default!;

}
