// <auto-generated>
// Code generated by OpenAPI Generator (aspnetcore-minimalapi)
// Changes to this file will be overwritten when regenerating.
// </auto-generated>

using System;
using System.Collections.Generic;
using PetstoreApi.Converters;

namespace PetstoreApi.DTOs;


/// <summary>
/// DTO for  operation
/// 
/// A tag for a pet
/// 
/// </summary>
public record TagDto
{


    /// <summary>
    /// 
    /// </summary>
    public long? Id { get; init; } = default!;

    /// <summary>
    /// 
    /// </summary>
    public string? Name { get; init; } = default!;

}
