// <auto-generated>
// Code generated by OpenAPI Generator (aspnetcore-minimalapi)
// Changes to this file will be overwritten when regenerating.
// </auto-generated>

using System;
using System.Collections.Generic;
using PetstoreApi.Converters;

namespace PetstoreApi.DTOs;

    /// <summary>
    /// Gets or Sets TestEnumDto
    /// </summary>
    [System.Text.Json.Serialization.JsonConverter(typeof(PetstoreApi.Converters.EnumMemberJsonConverter<TestEnumDto>))]
    public enum TestEnumDto
    {
        
        /// <summary>
        /// Enum AEnum for A
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("A")]
        AEnum = 1,
        
        /// <summary>
        /// Enum BEnum for B
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("B")]
        BEnum = 2
    }
