// <auto-generated>
// Code generated by OpenAPI Generator (aspnetcore-minimalapi)
// Changes to this file will be overwritten when regenerating.
// </auto-generated>

using System;
using System.Collections.Generic;
using PetstoreApi.Converters;

namespace PetstoreApi.DTOs;


/// <summary>
/// DTO for CreateUsersWithArrayInput operation
/// 
/// Creates list of users with given input array
/// 
/// </summary>
public record CreateUsersWithArrayInputDto
{
}
