// <auto-generated>
// Code generated by OpenAPI Generator (aspnetcore-minimalapi)
// Changes to this file will be overwritten when regenerating.
// </auto-generated>

using System;
using System.Collections.Generic;
using PetstoreApi.Converters;

namespace PetstoreApi.DTOs;


/// <summary>
/// DTO for PlaceOrder operation
/// 
/// Place an order for a pet
/// 
/// </summary>
public record PlaceOrderDto
{





    /// <summary>
    /// Order Status
    /// </summary>
    /// <value>Order Status</value>
    [System.Text.Json.Serialization.JsonConverter(typeof(PetstoreApi.Converters.EnumMemberJsonConverter<StatusEnum>))]
    public enum StatusEnum
    {
        
        /// <summary>
        /// Enum PlacedEnum for placed
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("placed")]
        PlacedEnum = 1,
        
        /// <summary>
        /// Enum ApprovedEnum for approved
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("approved")]
        ApprovedEnum = 2,
        
        /// <summary>
        /// Enum DeliveredEnum for delivered
        /// </summary>
        [System.Text.Json.Serialization.JsonPropertyName("delivered")]
        DeliveredEnum = 3
    }



    /// <summary>
    /// 
    /// </summary>
    public long? Id { get; init; } = default!;

    /// <summary>
    /// 
    /// </summary>
    public long? PetId { get; init; } = default!;

    /// <summary>
    /// 
    /// </summary>
    public int? Quantity { get; init; } = default!;

    /// <summary>
    /// 
    /// </summary>
    public DateTime? ShipDate { get; init; } = default!;

    /// <summary>
    /// Order Status
    /// </summary>
    [System.Text.Json.Serialization.JsonConverter(typeof(PetstoreApi.Converters.EnumMemberJsonConverter<StatusEnum>))]
    public StatusEnum? Status { get; init; } = default!;

    /// <summary>
    /// 
    /// </summary>
    public bool? Complete { get; init; } = default!;

}
