// <auto-generated>
// Code generated by OpenAPI Generator (aspnetcore-minimalapi)
// Changes to this file will be overwritten when regenerating.
// </auto-generated>

using System;
using System.Collections.Generic;
using PetstoreApi.Converters;

namespace PetstoreApi.DTOs;


/// <summary>
/// DTO for UpdateUser operation
/// 
/// Updated user
/// 
/// </summary>
public record UpdateUserDto
{








    /// <summary>
    /// 
    /// </summary>
    public long? Id { get; init; } = default!;

    /// <summary>
    /// 
    /// </summary>
    public string? Username { get; init; } = default!;

    /// <summary>
    /// 
    /// </summary>
    public string? FirstName { get; init; } = default!;

    /// <summary>
    /// 
    /// </summary>
    public string? LastName { get; init; } = default!;

    /// <summary>
    /// 
    /// </summary>
    public string? Email { get; init; } = default!;

    /// <summary>
    /// 
    /// </summary>
    public string? Password { get; init; } = default!;

    /// <summary>
    /// 
    /// </summary>
    public string? Phone { get; init; } = default!;

    /// <summary>
    /// User Status
    /// </summary>
    public int? UserStatus { get; init; } = default!;

}
