// <auto-generated>
// Code generated by OpenAPI Generator (aspnetcore-minimalapi)
// Changes to this file will be overwritten when regenerating.
// </auto-generated>

using MediatR;
using PetstoreApi.DTOs;

namespace PetstoreApi.Queries;

/// <summary>
/// Query for FakeNullableExampleTest operation
/// 
/// Fake endpoint to test nullable example (object)
/// 
/// </summary>
public record FakeNullableExampleTestQuery : IRequest<TestNullableDto>
{
}
