// <auto-generated>
// Code generated by OpenAPI Generator (aspnetcore-minimalapi)
// Changes to this file will be overwritten when regenerating.
// </auto-generated>

using MediatR;
using PetstoreApi.DTOs;

namespace PetstoreApi.Queries;

/// <summary>
/// Query for FakeParameterExampleTest operation
/// 
/// fake endpoint to test parameter example (object)
/// 
/// </summary>
public record FakeParameterExampleTestQuery : IRequest<Unit>
{
    /// <summary>
    /// 
    /// </summary>
    public PetDto data { get; init; }

}
