// <auto-generated>
// Code generated by OpenAPI Generator (aspnetcore-minimalapi)
// Changes to this file will be overwritten when regenerating.
// </auto-generated>

using MediatR;
using PetstoreApi.DTOs;

namespace PetstoreApi.Queries;

/// <summary>
/// Query for FindPetsByTags operation
/// 
/// Finds Pets by tags
/// 
/// </summary>
public record FindPetsByTagsQuery : IRequest<IEnumerable<PetDto>>
{
    /// <summary>
    /// Tags to filter by
    /// </summary>
    public string[] tags { get; init; }

}
