// <auto-generated>
// Code generated by OpenAPI Generator (aspnetcore-minimalapi)
// Changes to this file will be overwritten when regenerating.
// </auto-generated>

using MediatR;
using PetstoreApi.DTOs;

namespace PetstoreApi.Queries;

/// <summary>
/// Query for GetInventory operation
/// 
/// Returns pet inventories by status
/// 
/// </summary>
public record GetInventoryQuery : IRequest<Dictionary<string, int>>
{
}
