// <auto-generated>
// Code generated by OpenAPI Generator (aspnetcore-minimalapi)
// Changes to this file will be overwritten when regenerating.
// </auto-generated>

using MediatR;
using PetstoreApi.DTOs;

namespace PetstoreApi.Queries;

/// <summary>
/// Query for GetUserByName operation
/// 
/// Get user by user name
/// 
/// </summary>
public record GetUserByNameQuery : IRequest<UserDto>
{
    /// <summary>
    /// The name that needs to be fetched. Use user1 for testing.
    /// </summary>
    public string username { get; init; }

}
