// <auto-generated>
// Code generated by OpenAPI Generator (aspnetcore-minimalapi)
// Changes to this file will be overwritten when regenerating.
// </auto-generated>

using MediatR;
using PetstoreApi.DTOs;

namespace PetstoreApi.Queries;

/// <summary>
/// Query for LoginUser operation
/// 
/// Logs user into the system
/// 
/// </summary>
public record LoginUserQuery : IRequest<string>
{
    /// <summary>
    /// The user name for login
    /// </summary>
    public string username { get; init; }

    /// <summary>
    /// The password for login in clear text
    /// </summary>
    public string password { get; init; }

}
