// <auto-generated>
// Code generated by OpenAPI Generator (aspnetcore-minimalapi)
// Changes to this file will be overwritten when regenerating.
// </auto-generated>

using MediatR;
using PetstoreApi.DTOs;

namespace PetstoreApi.Queries;

/// <summary>
/// Query for LogoutUser operation
/// 
/// Logs out current logged in user session
/// 
/// </summary>
public record LogoutUserQuery : IRequest<Unit>
{
}
