// <auto-generated>
// Code generated by OpenAPI Generator (aspnetcore-minimalapi)
// Changes to this file will be overwritten when regenerating.
// </auto-generated>

using MediatR;
using PetstoreApi.DTOs;

namespace PetstoreApi.Queries;

/// <summary>
/// Query for TestGet operation
/// 
/// Test API
/// 
/// </summary>
public record TestGetQuery : IRequest<Unit>
{
    /// <summary>
    /// 
    /// </summary>
    public TestEnumDto? testQuery { get; init; } = default!;

}
