// <auto-generated>
// Code generated by OpenAPI Generator (aspnetcore-minimalapi)
// Changes to this file will be overwritten when regenerating.
// </auto-generated>

using FluentValidation;
using PetstoreApi.DTOs;

namespace PetstoreApi.Validators;

/// <summary>
/// Validator for AddPetDto
/// 
/// Validates AddPet request
/// 
/// </summary>
public class AddPetDtoValidator : AbstractValidator<AddPetDto>
{
    public AddPetDtoValidator()
    {
        // Nested object validation
        RuleFor(x => x.Category)
            .SetValidator(new CategoryDtoValidator())
            .When(x => x.Category != null);
        // Required field validation
        RuleFor(x => x.Name)
            .NotEmpty()
            .WithMessage("Name is required");
        // String length validation
        RuleFor(x => x.Name)
            .Length(2, 100)
            .WithMessage("Name must be between 2 and 100 characters");
        // Required field validation
        RuleFor(x => x.PhotoUrls)
            .NotEmpty()
            .WithMessage("PhotoUrls is required");
        // Array size validation
        RuleFor(x => x.PhotoUrls)
            .Must(x => x != null && x.Count >= 1 && x.Count <= 10)
            .WithMessage("PhotoUrls must contain between 1 and 10 items");
        // TODO: Nested array validation requires proper DTO type mapping
        // RuleForEach validation for complex array items will be added in future enhancement
        // Enum validation
        RuleFor(x => x.Status)
            .Must(value => value == null || Enum.IsDefined(typeof(AddPetDto.StatusEnum), value.Value))
            .WithMessage("Status must be a valid enum value");
    }
}
