// <auto-generated>
// Code generated by OpenAPI Generator (aspnetcore-minimalapi)
// Changes to this file will be overwritten when regenerating.
// </auto-generated>

using FluentValidation;
using PetstoreApi.DTOs;

namespace PetstoreApi.Validators;

/// <summary>
/// Validator for CreateUsersWithArrayInputDto
/// 
/// Validates CreateUsersWithArrayInput request
/// 
/// </summary>
public class CreateUsersWithArrayInputDtoValidator : AbstractValidator<CreateUsersWithArrayInputDto>
{
    public CreateUsersWithArrayInputDtoValidator()
    {
    }
}
