// <auto-generated>
// Code generated by OpenAPI Generator (aspnetcore-minimalapi)
// Changes to this file will be overwritten when regenerating.
// </auto-generated>

using FluentValidation;
using PetstoreApi.DTOs;

namespace PetstoreApi.Validators;

/// <summary>
/// Validator for PlaceOrderDto
/// 
/// Validates PlaceOrder request
/// 
/// </summary>
public class PlaceOrderDtoValidator : AbstractValidator<PlaceOrderDto>
{
    public PlaceOrderDtoValidator()
    {
        // Minimum value validation
        RuleFor(x => x.Quantity)
            .GreaterThanOrEqualTo(1)
            .WithMessage("Quantity must be at least 1");
        // Maximum value validation
        RuleFor(x => x.Quantity)
            .LessThanOrEqualTo(100)
            .WithMessage("Quantity must not exceed 100");
        // Enum validation
        RuleFor(x => x.Status)
            .Must(value => value == null || Enum.IsDefined(typeof(PlaceOrderDto.StatusEnum), value.Value))
            .WithMessage("Status must be a valid enum value");
    }
}
