// <auto-generated>
// Code generated by OpenAPI Generator (aspnetcore-minimalapi)
// Changes to this file will be overwritten when regenerating.
// </auto-generated>

using FluentValidation;
using PetstoreApi.DTOs;

namespace PetstoreApi.Validators;

/// <summary>
/// Validator for UpdateUserDto
/// 
/// Validates UpdateUser request
/// 
/// </summary>
public class UpdateUserDtoValidator : AbstractValidator<UpdateUserDto>
{
    public UpdateUserDtoValidator()
    {
        // String length validation
        RuleFor(x => x.Username)
            .Length(3, 50)
            .WithMessage("Username must be between 3 and 50 characters");
        // Pattern validation
        RuleFor(x => x.Email)
            .Matches(@"^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$")
            .WithMessage("Email must match the specified pattern");
        // Minimum string length validation
        RuleFor(x => x.Password)
            .MinimumLength(8)
            .WithMessage("Password must be at least 8 characters");
    }
}
