// <auto-generated>
// Code generated by OpenAPI Generator (aspnetcore-minimalapi)
// Changes to this file will be overwritten when regenerating.
// </auto-generated>

using FluentValidation;
using PetstoreApi.DTOs;

namespace PetstoreApi.Validators;

/// <summary>
/// Validator for CategoryDto
/// 
/// Validates  request
/// 
/// </summary>
public class CategoryDtoValidator : AbstractValidator<CategoryDto>
{
    public CategoryDtoValidator()
    {
        // Pattern validation
        RuleFor(x => x.Name)
            .Matches(@"^[a-zA-Z0-9]+[a-zA-Z0-9\.\-_]*[a-zA-Z0-9]+$")
            .WithMessage("Name must match the specified pattern");
    }
}
