// <auto-generated>
// Code generated by OpenAPI Generator (aspnetcore-minimalapi)
// Changes to this file will be overwritten when regenerating.
// </auto-generated>

using FluentValidation;
using PetstoreApi.DTOs;

namespace PetstoreApi.Validators;

/// <summary>
/// Validator for CreateUsersWithListInputDto
/// 
/// Validates CreateUsersWithListInput request
/// 
/// </summary>
public class CreateUsersWithListInputDtoValidator : AbstractValidator<CreateUsersWithListInputDto>
{
    public CreateUsersWithListInputDtoValidator()
    {
    }
}
