// <auto-generated>
// Code generated by OpenAPI Generator (aspnetcore-minimalapi)
// Changes to this file will be overwritten when regenerating.
// </auto-generated>

using MediatR;
using PetstoreApi.DTOs;

namespace PetstoreApi.Commands;

/// <summary>
/// Command for AddPet operation
/// 
/// Add a new pet to the store
/// 
/// </summary>
public record AddPetCommand : IRequest<PetDto>
{
    /// <summary>
    /// Pet object that needs to be added to the store
    /// </summary>
    public AddPetDto pet { get; init; }

}
