// <auto-generated>
// Code generated by OpenAPI Generator (aspnetcore-minimalapi)
// Changes to this file will be overwritten when regenerating.
// </auto-generated>

using MediatR;
using PetstoreApi.DTOs;

namespace PetstoreApi.Commands;

/// <summary>
/// Command for DeleteUser operation
/// 
/// Delete user
/// 
/// </summary>
public record DeleteUserCommand : IRequest<bool>
{
    /// <summary>
    /// The name that needs to be deleted
    /// </summary>
    public string username { get; init; }

}
