// <auto-generated>
// Code generated by OpenAPI Generator (aspnetcore-minimalapi)
// Changes to this file will be overwritten when regenerating.
// </auto-generated>

using MediatR;
using PetstoreApi.DTOs;

namespace PetstoreApi.Commands;

/// <summary>
/// Command for UpdatePet operation
/// 
/// Update an existing pet
/// 
/// </summary>
public record UpdatePetCommand : IRequest<PetDto>
{
    /// <summary>
    /// Pet object that needs to be added to the store
    /// </summary>
    public UpdatePetDto pet { get; init; }

}
